### PR TITLE
Fix for Android 13

### PR DESCRIPTION
**Pull request by carlpach**
Bug: Photos didn't enlarge in the device when clicked

### CODE REVIEW

**Comment by carlpach** [comment]
@cauboy, Could you give me write access to the repo?

there is a bug for Android user not being able to enlarge the photos when clicked in the app. It has been reported by 3 users in less than 2 weeks.
I just found this fork from the original plugin repo which solves the issue. I tested in my device and works fine.
thanks!

**Comment by cauboy** [comment]
With original plugin you mean https://github.com/AbidR-S2/photoviewer/tree/master?

Just asking because the original would be https://github.com/sarriaroman/photoviewer which wasn't updated for years

**Review by cauboy — APPROVED** [review]
@carlpach There are conflicts so we cannot easily merge it. Can you have a look?

**Comment by carlpach** [comment]
@cauboy 
- With original plugin I mean the one we currently have, which isn't working. The merge I suggest in the PR is from the fork https://github.com/AbidR-S2/photoviewer/tree/master
- I cannot see the conflicts unless you give me write access

**Pull request merged**
